name: myddasp
channels:
  - conda-forge
  - defaults
dependencies:
  - python  # 3.11.6
  - pip  # 23.3
  - black  # 23.10.0
  - jupyter-black  # 0.3.4
  - ipykernel  # 6.25.2
  - jupyterlab  # 4.0.7
  - matplotlib  # 3.8.0
  - ipympl  # 0.9.3
  - numpy  # 1.25.2
  - scipy  # 1.11.3
  - scikit-learn  # 1.3.1
  - statsmodels  # 0.14.0
  - tensorflow  # 2.12.1
  - keras-tuner  # 1.3.5
  - librosa  # 0.10.1
  - pip:
    - pyloudnorm==0.1.0
# conda env remove -n myddasp
# conda env create -f environment.yml
# pip manually?!
# python -m ipykernel install --user --name myddasp --display-name "myddasp"
