# this file was taken from the lecture
# Sascha Spors: "Continuous- and Discrete-Time Signals and Systems - Theory and Computational Examples"
# see
# https://github.com/spatialaudio/signals-and-systems-lecture/blob/master/.github/workflows/notebook_ci.yml
# executes all cells (e.g. numerical examples) in all notebooks
# by using sphinx with the nbsphinx extension

name: Integration Test

on:
  pull_request:

  schedule:
    - cron:  '30 1 1,15 * *'

jobs:
  linux_py310:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: sudo apt-get install pandoc
      - run: pip install -r ci/requirements_env.txt
      - run: pip install -r ci/requirements_ci.txt
      - run: python -m sphinx . _build/ -b html

  linux_py311:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: sudo apt-get install pandoc
      - run: pip install -r ci/requirements_env.txt
      - run: pip install -r ci/requirements_ci.txt
      - run: python -m sphinx . _build/ -b html
